:start ::= ROOTS

ROOTS ::= ROOT+

ROOT ::= TYPE period

TYPE ::= S
| SBAR
| SBARQ
| SQ

S ::= NP
| NP VP
| SBAR S
| VP

SBARQ ::= WHNP SQ

SQ ::= S

SBAR ::= WHNP S
| S

NP ::= DT
| DT NP
| IN NP
| JJ NP
| NN
| NNS
| NP CC NP
| PRP
| RB NP

VP ::= MD VP
| TO VP
| VB
| VBG
| VBP RB S
| VBP S
| VBZ JJ S
| VBZ RB S
| VBZ S
| WBD

WHNP ::= WP

CC  ~ /and|as/i
DT  ~ /all|this|that|these|those|a|the/i
IN  ~ /for|about|into|in|out|of|as|with/i
JJ  ~ /any|full|good|kind|your|my/i
MD  ~ /would/i
NN  ~ /time|door|girl|something|idea|picture|yard|pencil|book|address|name|color|size|day|today|milk|question|mine|yours|plan/i
NNS ~ /children|books|pencils|letters|cats|dogs|eggs/i
PRP ~ /it|you|me|he|her|we|of|i/i
RB  ~ /too|not|very|exactly|early/i
TO  ~ /to/i
VB  ~ /eat|do|add|be|want|learn|like/i
VBG ~ /going/i
VBP ~ /are|have|suggest/i
VBZ ~ /is|'s/i
WBD ~ /said/i
WP  ~ /what/i

comma  ~ ','
hyphen ~ '-'
period ~ /\.|\?|\!/

# Allow comments
:discard ~ <hash comment>
<hash comment> ~ /#[^\n]*/

:discard ~ whitespace
whitespace ~ [\s]+

# :discard ~ word
word ~ /'?\w+/