:start ::= ROOTS

ROOTS ::= ROOT+

ROOT ::= TYPE period

TYPE ::= S
| SBAR
| SBARQ
| SQ

S ::=  NP VP
|| VP
|| NP
| SBAR S

SBARQ ::= WHNP SQ

SQ ::= S

SBAR ::= WHNP S
| S

NP ::= DT
| DT NP
| IN NP
| JJ NP
| NN
| NNS
| NP CC NP
| PRP
| RB NP

VP ::= MD VP
| TO VP
| VB NP
| VBG
| VBP RB S
| VBP S
| VBZ JJ S
| VBZ RB S
| VBZ S
| WBD

WHNP ::= WP

# Penn Treebank tagset, for more information see
# https://www.sketchengine.eu/penn-treebank-tagset/
CC  ~ /and|as/i
DT  ~ /all|this|that|these|those|a|an|the/i
IN  ~ /like|over|for|about|into|in|out|of|as|with/i
JJ  ~ /lazy|brown|quick|any|full|good|kind|your|my/i
MD  ~ /can|could|might|may|would/i
NN  ~ /dog|fox|time|door|girl|something|idea|picture|yard|pencil|book|address|name|color|size|day|today|milk|question|mine|yours|plan/i
NNS ~ /children|books|pencils|letters|cats|dogs|eggs/i
PRP ~ /it|you|me|he|her|we|of|i/i
RB  ~ /too|not|very|exactly|early/i
TO  ~ /to/i
VB  ~ /like|eat|do|add|be|want|learn/i
VBG ~ /going/i
VBP ~ /like|are|have|suggest/i
VBZ ~ /jumps|is|'s/i
WBD ~ /said/i
WP  ~ /what|who|whom/i

comma  ~ ','
period ~ /\.|\?|\!/

# Allow comments
:discard ~ <hash comment>
<hash comment> ~ /#[^\n]*/

:discard ~ whitespace
whitespace ~ [\s]+
