:start ::= TAGS
TAGS ::= TAG+
TAG ::= TAG_BYTE
| TAG_SHORT
| TAG_INT
| TAG_LONG
| TAG_FLOAT 
| TAG_DOUBLE
| TAG_BYTE_ARRAY
| TAG_STRING
| TAG_LIST
| TAG_COMPOUND
| TAG_INT_ARRAY 
| TAG_LONG_ARRAY

TAG_BYTE ::= BYTE_ID SIZE NAME BYTE_PAYLOAD
BYTE_ID ~ /\x01/
BYTE_PAYLOAD ::= BYTE

TAG_SHORT ::= SHORT_ID SIZE NAME SHORT_PAYLOD
SHORT_ID ~ /\x02/
SHORT_PAYLOD ::= BYTE BYTE

TAG_INT ::= INT_ID SIZE NAME INT_PAYLOAD
INT_ID ~ /\x03/
INT_PAYLOAD ::= BYTE BYTE BYTE BYTE

TAG_LONG ::= LONG_ID SIZE NAME LONG_PAYLOAD
LONG_ID ~ /\x04/
LONG_PAYLOAD ::= BYTE BYTE BYTE BYTE BYTE BYTE BYTE BYTE

TAG_FLOAT ::= FLOAT_ID SIZE NAME FLOAT_PAYLOAD
FLOAT_ID ~ /\x05/
FLOAT_PAYLOAD ::= BYTE BYTE BYTE BYTE

TAG_DOUBLE ::= DOUBLE_ID SIZE NAME DOUBLE_PAYLOAD
DOUBLE_ID ~ /\x06/
DOUBLE_PAYLOAD ::= BYTE BYTE BYTE BYTE BYTE BYTE BYTE BYTE

TAG_BYTE_ARRAY ::= BYTE_ARRAY_ID SIZE NAME BYTE_ARRAY_PAYLOAD
BYTE_ARRAY_ID ~ /\x07/
BYTE_ARRAY_PAYLOAD ::= TAG_BYTE+

TAG_STRING ::= STRING_ID SIZE NAME STRING_PAYLOAD
STRING_ID ~ /\x08/
STRING_PAYLOAD ::= SIZE NAME

TAG_LIST ::= LIST_ID SIZE NAME LIST_PAYLOAD
LIST_ID ~ /\x09/
LIST_PAYLOAD ::= BYTE BYTE TAGS

TAG_COMPOUND ::= COMPOUND_ID SIZE NAME TAGS END
COMPOUND_ID ~ /\x0a/
END ~ /\x00/

TAG_INT_ARRAY ::= INT_ARRAY_ID SIZE NAME INT_ARRAY_PAYLOAD
INT_ARRAY_ID ~ /\x0b/
INT_ARRAY_PAYLOAD ::= TAG_INT*

TAG_LONG_ARRAY ::= LONG_ARRAY_ID SIZE NAME LONG_ARRAY_PAYLOAD
LONG_ARRAY_ID ~ /\x0c/
LONG_ARRAY_PAYLOAD ::= TAG_LONG*

SIZE ~ BYTE BYTE
BYTE ~ /[\x00-\xff]|./
NAME ~ /([A-Ö]|\s)+/u
