module Marpa
  errors = [
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NONE, "MARPA_ERR_NONE", "No error"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_AHFA_IX_NEGATIVE, "MARPA_ERR_AHFA_IX_NEGATIVE", "AHFA index negative"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_AHFA_IX_OOB, "MARPA_ERR_AHFA_IX_OOB", "AHFA index out of bounds"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_ANDID_NEGATIVE, "MARPA_ERR_ANDID_NEGATIVE", "AND ID negative"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_ANDID_NOT_IN_OR, "MARPA_ERR_ANDID_NOT_IN_OR", "AND ID not in or"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_ANDIX_NEGATIVE, "MARPA_ERR_ANDIX_NEGATIVE", "AND index negative"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_BAD_SEPARATOR, "MARPA_ERR_BAD_SEPARATOR", "Separator has invalid symbol ID"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_BOCAGE_ITERATION_EXHAUSTED, "MARPA_ERR_BOCAGE_ITERATION_EXHAUSTED", "Bocage iteration exhausted"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_COUNTED_NULLABLE, "MARPA_ERR_COUNTED_NULLABLE", "Nullable symbol on RHS of a sequence rule"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_DEVELOPMENT, "MARPA_ERR_DEVELOPMENT", "Development error, see string"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_DUPLICATE_AND_NODE, "MARPA_ERR_DUPLICATE_AND_NODE", "Duplicate AND node"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_DUPLICATE_RULE, "MARPA_ERR_DUPLICATE_RULE", "Duplicate rule"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_DUPLICATE_TOKEN, "MARPA_ERR_DUPLICATE_TOKEN", "Duplicate token"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_YIM_COUNT, "MARPA_ERR_YIM_COUNT", "Maximum number of Earley items exceeded"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_YIM_ID_INVALID, "MARPA_ERR_YIM_ID_INVALID", "Invalid Earley item (YIM)"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_EVENT_IX_NEGATIVE, "MARPA_ERR_EVENT_IX_NEGATIVE", "Negative event index"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_EVENT_IX_OOB, "MARPA_ERR_EVENT_IX_OOB", "No event at that index"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_GRAMMAR_HAS_CYCLE, "MARPA_ERR_GRAMMAR_HAS_CYCLE", "Grammar has cycle"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_INACCESSIBLE_TOKEN, "MARPA_ERR_INACCESSIBLE_TOKEN", "Token symbol is inaccessible"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_INTERNAL, "MARPA_ERR_INTERNAL", "Internal error"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_INVALID_AHFA_ID, "MARPA_ERR_INVALID_AHFA_ID", "Invalid Aycock-Horspool Finite Automaton (AHFA) ID"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_INVALID_AIMID, "MARPA_ERR_INVALID_AIMID", "Invalid Aycock-Horspool item (AIM) ID"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_INVALID_BOOLEAN, "MARPA_ERR_INVALID_BOOLEAN", "Argument is not boolean"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_INVALID_IRLID, "MARPA_ERR_INVALID_IRLID", "Invalid internal rule (IRL) ID"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_INVALID_NSYID, "MARPA_ERR_INVALID_NSYID", "Invalid external symbol (NSY) ID"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_INVALID_LOCATION, "MARPA_ERR_INVALID_LOCATION", "Location is not valid"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_INVALID_RULE_ID, "MARPA_ERR_INVALID_RULE_ID", "Rule ID is malformed"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_INVALID_START_SYMBOL, "MARPA_ERR_INVALID_START_SYMBOL", "Specified start symbol is not valid"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_INVALID_SYMBOL_ID, "MARPA_ERR_INVALID_SYMBOL_ID", "Symbol ID is malformed"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_I_AM_NOT_OK, "MARPA_ERR_I_AM_NOT_OK", "Marpa is in a not OK state"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_MAJOR_VERSION_MISMATCH, "MARPA_ERR_MAJOR_VERSION_MISMATCH", "Libmarpa major version number is a mismatch"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_MICRO_VERSION_MISMATCH, "MARPA_ERR_MICRO_VERSION_MISMATCH", "Libmarpa micro version number is a mismatch"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_MINOR_VERSION_MISMATCH, "MARPA_ERR_MINOR_VERSION_MISMATCH", "Libmarpa minor version number is a mismatch"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NOOKID_NEGATIVE, "MARPA_ERR_NOOKID_NEGATIVE", "Nook ID negative"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NOT_PRECOMPUTED, "MARPA_ERR_NOT_PRECOMPUTED", "This grammar is not precomputed"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NOT_TRACING_COMPLETION_LINKS, "MARPA_ERR_NOT_TRACING_COMPLETION_LINKS", "Not tracing completion links"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NOT_TRACING_LEO_LINKS, "MARPA_ERR_NOT_TRACING_LEO_LINKS", "Not tracing Leo links"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NOT_TRACING_TOKEN_LINKS, "MARPA_ERR_NOT_TRACING_TOKEN_LINKS", "Not tracing token links"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NO_AND_NODES, "MARPA_ERR_NO_AND_NODES", "MARPA_ERR_NO_AND_NODES"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NO_EARLEY_SET_AT_LOCATION, "MARPA_ERR_NO_EARLEY_SET_AT_LOCATION", "Earley set ID is after latest Earley set"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NO_OR_NODES, "MARPA_ERR_NO_OR_NODES", "MARPA_ERR_NO_OR_NODES"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NO_PARSE, "MARPA_ERR_NO_PARSE", "No parse"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NO_RULES, "MARPA_ERR_NO_RULES", "This grammar does not have any rules"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NO_START_SYMBOL, "MARPA_ERR_NO_START_SYMBOL", "This grammar has no start symbol"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NO_TOKEN_EXPECTED_HERE, "MARPA_ERR_NO_TOKEN_EXPECTED_HERE", "No token is expected at this earleme location"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NO_TRACE_YIM, "MARPA_ERR_NO_TRACE_YIM", "MARPA_ERR_NO_TRACE_YIM"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NO_TRACE_YS, "MARPA_ERR_NO_TRACE_YS", "MARPA_ERR_NO_TRACE_YS"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NO_TRACE_PIM, "MARPA_ERR_NO_TRACE_PIM", "MARPA_ERR_NO_TRACE_PIM"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NO_TRACE_SRCL, "MARPA_ERR_NO_TRACE_SRCL", "MARPA_ERR_NO_TRACE_SRCL"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NULLING_TERMINAL, "MARPA_ERR_NULLING_TERMINAL", "A symbol is both terminal and nulling"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_ORDER_FROZEN, "MARPA_ERR_ORDER_FROZEN", "The ordering is frozen"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_ORID_NEGATIVE, "MARPA_ERR_ORID_NEGATIVE", "MARPA_ERR_ORID_NEGATIVE"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_OR_ALREADY_ORDERED, "MARPA_ERR_OR_ALREADY_ORDERED", "MARPA_ERR_OR_ALREADY_ORDERED"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_PARSE_EXHAUSTED, "MARPA_ERR_PARSE_EXHAUSTED", "The parse is exhausted"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_PARSE_TOO_LONG, "MARPA_ERR_PARSE_TOO_LONG", "This input would make the parse too long"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_PIM_IS_NOT_LIM, "MARPA_ERR_PIM_IS_NOT_LIM", "MARPA_ERR_PIM_IS_NOT_LIM"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_POINTER_ARG_NULL, "MARPA_ERR_POINTER_ARG_NULL", "An argument is null when it should not be"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_PRECOMPUTED, "MARPA_ERR_PRECOMPUTED", "This grammar is precomputed"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_PROGRESS_REPORT_EXHAUSTED, "MARPA_ERR_PROGRESS_REPORT_EXHAUSTED", "The progress report is exhausted"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_PROGRESS_REPORT_NOT_STARTED, "MARPA_ERR_PROGRESS_REPORT_NOT_STARTED", "No progress report has been started"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_RECCE_NOT_ACCEPTING_INPUT, "MARPA_ERR_RECCE_NOT_ACCEPTING_INPUT", "The recognizer is not accepting input"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_RECCE_NOT_STARTED, "MARPA_ERR_RECCE_NOT_STARTED", "The recognizer has not been started"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_RECCE_STARTED, "MARPA_ERR_RECCE_STARTED", "The recognizer has been started"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_RHS_IX_NEGATIVE, "MARPA_ERR_RHS_IX_NEGATIVE", "RHS index cannot be negative"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_RHS_IX_OOB, "MARPA_ERR_RHS_IX_OOB", "RHS index must be less than rule length"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_RHS_TOO_LONG, "MARPA_ERR_RHS_TOO_LONG", "The RHS is too long"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_SEQUENCE_LHS_NOT_UNIQUE, "MARPA_ERR_SEQUENCE_LHS_NOT_UNIQUE", "LHS of sequence rule would not be unique"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_SOURCE_TYPE_IS_AMBIGUOUS, "MARPA_ERR_SOURCE_TYPE_IS_AMBIGUOUS", "Internal error: MARPA_ERR_SOURCE_TYPE_IS_AMBIGUOUS"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_SOURCE_TYPE_IS_COMPLETION, "MARPA_ERR_SOURCE_TYPE_IS_COMPLETION", "Internal error: MARPA_ERR_SOURCE_TYPE_IS_COMPLETION"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_SOURCE_TYPE_IS_LEO, "MARPA_ERR_SOURCE_TYPE_IS_LEO", "Internal error: MARPA_ERR_SOURCE_TYPE_IS_LEO"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_SOURCE_TYPE_IS_NONE, "MARPA_ERR_SOURCE_TYPE_IS_NONE", "Internal error: MARPA_ERR_SOURCE_TYPE_IS_NONE"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_SOURCE_TYPE_IS_TOKEN, "MARPA_ERR_SOURCE_TYPE_IS_TOKEN", "Internal error: MARPA_ERR_SOURCE_TYPE_IS_TOKEN"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_SOURCE_TYPE_IS_UNKNOWN, "MARPA_ERR_SOURCE_TYPE_IS_UNKNOWN", "Internal error: MARPA_ERR_SOURCE_TYPE_IS_UNKNOWN"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_START_NOT_LHS, "MARPA_ERR_START_NOT_LHS", "Start symbol not on LHS of any rule"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_SYMBOL_VALUED_CONFLICT, "MARPA_ERR_SYMBOL_VALUED_CONFLICT", "Symbol is treated both as valued and unvalued"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_TERMINAL_IS_LOCKED, "MARPA_ERR_TERMINAL_IS_LOCKED", "The terminal status of the symbol is locked"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_TOKEN_IS_NOT_TERMINAL, "MARPA_ERR_TOKEN_IS_NOT_TERMINAL", "Token symbol must be a terminal"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_TOKEN_LENGTH_LE_ZERO, "MARPA_ERR_TOKEN_LENGTH_LE_ZERO", "Token length must greater than zero"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_TOKEN_TOO_LONG, "MARPA_ERR_TOKEN_TOO_LONG", "Token is too long"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_TREE_EXHAUSTED, "MARPA_ERR_TREE_EXHAUSTED", "Tree iterator is exhausted"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_TREE_PAUSED, "MARPA_ERR_TREE_PAUSED", "Tree iterator is paused"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_UNEXPECTED_TOKEN_ID, "MARPA_ERR_UNEXPECTED_TOKEN_ID", "Unexpected token ID"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_UNPRODUCTIVE_START, "MARPA_ERR_UNPRODUCTIVE_START", "Unproductive start symbol"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_VALUATOR_INACTIVE, "MARPA_ERR_VALUATOR_INACTIVE", "Valuator inactive"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_VALUED_IS_LOCKED, "MARPA_ERR_VALUED_IS_LOCKED", "The valued status of the symbol is locked"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_RANK_TOO_LOW, "MARPA_ERR_RANK_TOO_LOW", "Rule or symbol rank too low"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_RANK_TOO_HIGH, "MARPA_ERR_RANK_TOO_HIGH", "Rule or symbol rank too high"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_SYMBOL_IS_NULLING, "MARPA_ERR_SYMBOL_IS_NULLING", "Symbol is nulling"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_SYMBOL_IS_UNUSED, "MARPA_ERR_SYMBOL_IS_UNUSED", "Symbol is not used"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NO_SUCH_RULE_ID, "MARPA_ERR_NO_SUCH_RULE_ID", "No rule with this ID exists"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NO_SUCH_SYMBOL_ID, "MARPA_ERR_NO_SUCH_SYMBOL_ID", "No symbol with this ID exists"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_BEFORE_FIRST_TREE, "MARPA_ERR_BEFORE_FIRST_TREE", "Tree iterator is before first tree"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_SYMBOL_IS_NOT_COMPLETION_EVENT, "MARPA_ERR_SYMBOL_IS_NOT_COMPLETION_EVENT", "Symbol is not set up for completion events"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_SYMBOL_IS_NOT_NULLED_EVENT, "MARPA_ERR_SYMBOL_IS_NOT_NULLED_EVENT", "Symbol is not set up for nulled events"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_SYMBOL_IS_NOT_PREDICTION_EVENT, "MARPA_ERR_SYMBOL_IS_NOT_PREDICTION_EVENT", "Symbol is not set up for prediction events"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_RECCE_IS_INCONSISTENT, "MARPA_ERR_RECCE_IS_INCONSISTENT", "MARPA_ERR_RECCE_IS_INCONSISTENT"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_INVALID_ASSERTION_ID, "MARPA_ERR_INVALID_ASSERTION_ID", "Assertion ID is malformed"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NO_SUCH_ASSERTION_ID, "MARPA_ERR_NO_SUCH_ASSERTION_ID", "No assertion with this ID exists"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_HEADERS_DO_NOT_MATCH, "MARPA_ERR_HEADERS_DO_NOT_MATCH", "Internal error: Libmarpa was built incorrectly"},
    {LibMarpa::MarpaErrorCode::MARPA_ERR_NOT_A_SEQUENCE, "MARPA_ERR_NOT_A_SEQUENCE", "Rule is not a sequence"},
  ]

  events = [
    {LibMarpa::MarpaEventType::MARPA_EVENT_NONE, "MARPA_EVENT_NONE", "No event"},
    {LibMarpa::MarpaEventType::MARPA_EVENT_COUNTED_NULLABLE, "MARPA_EVENT_COUNTED_NULLABLE", "This symbol is a counted nullable"},
    {LibMarpa::MarpaEventType::MARPA_EVENT_EARLEY_ITEM_THRESHOLD, "MARPA_EVENT_EARLEY_ITEM_THRESHOLD", "Too many Earley items"},
    {LibMarpa::MarpaEventType::MARPA_EVENT_EXHAUSTED, "MARPA_EVENT_EXHAUSTED", "Recognizer is exhausted"},
    {LibMarpa::MarpaEventType::MARPA_EVENT_LOOP_RULES, "MARPA_EVENT_LOOP_RULES", "Grammar contains a infinite loop"},
    {LibMarpa::MarpaEventType::MARPA_EVENT_NULLING_TERMINAL, "MARPA_EVENT_NULLING_TERMINAL", "This symbol is a nulling terminal"},
    {LibMarpa::MarpaEventType::MARPA_EVENT_SYMBOL_COMPLETED, "MARPA_EVENT_SYMBOL_COMPLETED", "Completed symbol"},
    {LibMarpa::MarpaEventType::MARPA_EVENT_SYMBOL_EXPECTED, "MARPA_EVENT_SYMBOL_EXPECTED", "Expecting symbol"},
    {LibMarpa::MarpaEventType::MARPA_EVENT_SYMBOL_NULLED, "MARPA_EVENT_SYMBOL_NULLED", "Symbol was nulled"},
    {LibMarpa::MarpaEventType::MARPA_EVENT_SYMBOL_PREDICTED, "MARPA_EVENT_SYMBOL_PREDICTED", "Symbol was predicted"},
  ]

  steps = [
    {LibMarpa::MarpaStepType::MARPA_STEP_INTERNAL1, "MARPA_STEP_INTERNAL1", "Internal valuation step 1"},
    {LibMarpa::MarpaStepType::MARPA_STEP_RULE, "MARPA_STEP_RULE", "Rule valuation step"},
    {LibMarpa::MarpaStepType::MARPA_STEP_TOKEN, "MARPA_STEP_TOKEN", "Non-null token valuation step"},
    {LibMarpa::MarpaStepType::MARPA_STEP_NULLING_SYMBOL, "MARPA_STEP_NULLING_SYMBOL", "Nulling symbol valuation step"},
    {LibMarpa::MarpaStepType::MARPA_STEP_TRACE, "MARPA_STEP_TRACE", "Trace valuation step"},
    {LibMarpa::MarpaStepType::MARPA_STEP_INACTIVE, "MARPA_STEP_INACTIVE", "Inactive valuation step after all steps completed"},
    {LibMarpa::MarpaStepType::MARPA_STEP_INTERNAL2, "MARPA_STEP_INTERNAL2", "Internal step 2"},
    {LibMarpa::MarpaStepType::MARPA_STEP_INITIAL, "MARPA_STEP_INITIAL", "Initial step before any step is completed"},
  ]
end
