:start ::= rules
rules ::= rule+

rule ::= cmd_type user
    | cmd_type list_ref
    | user_list

user_list  ::= user '=' users
users      ::= user+

list_ref        ~ '@' username
user            ~ username

cmd_type        ~ 'Deny' | 'Allow'
username        ~ [\w]+

:discard        ~ ws
ws              ~ [\s]+