:start ::= json
json ::= value

object ::= '{' members '}'
members ::= pair* proper => 1 separator => comma
pair ::= string ':' value

value ::= string | object | number | array | true | false | null

array ::= '[' elements ']'
elements ::= value* proper => 1 separator => comma

comma ~ ','

# TODO: Split regex into bite-sized pieces
string ~ /"([^"\\]*|\\["\\bfnrt\/]|\\u[0-9a-f]{4})*"/
number ~ /-?(?=[1-9]|0(?!\d))\d+(\.\d+)?([eE][+-]?\d+)?/

true ~ 'true'
false ~ 'false'
null ~ 'null'

:discard ~ whitespace
whitespace ~ [\s]+